# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tim Acosta
title: Android Developer
email: timacosta06@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  timacosta
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: tim-acosta
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Medium
  icon: fab fa-medium
  url: https://medium.com/@timacosta06
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Tim and I'm a software developer with a focus on mobile applications and Android development.

  I am most skilled in: <mark>Android</mark> and <mark>Kotlin</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: JetPackAtlas
        link: github.com/timacosta
        # link_text: Project Website
        additional_links:
          - title:  timacosta/JetpackAtlas
            icon: fab fa-github
            url: https://github.com/timacosta/JetpackAtlas
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Jetpack Compose Travel sample app using Clean Architecture + MVVM
        description: | # this will include new lines to allow paragraphs
          I started this project as a way to learn about <mark>Jetpack Compose</mark> animations and it has since grown into a fully fledged app. I use this also as a sample for some of my Medium articles. 

      - layout: top-middle
        title: PokeArch
        link: github.com/timacosta
        # link_text: Project Website
        additional_links:
          - title:  timacosta/PokeArch
            icon: fab fa-github
            url: https://github.com/timacosta/PokeArch
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Jetpack Compose Pokedex App using Clean Architecture + MVVM
        description: | # this will include new lines to allow paragraphs
          Project specifically build for Architect Coders by Antonio Leiva, using <mark>Jetpack Compose</mark>.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Auxmoney
        link: https://www.auxmoney.com
        # link_text: boringcompany.com
        sub_title: Android Developer
        caption: November 2021 - Present
        quote: >
          auxmoney, a Düsseldorf, Germany-headquartered company building a digital lending platform for consumer credit in Europe
        description: | # this will include new lines to allow paragraphs
            Building, mantaining and improving the Auxmoney Android App, +100K downloads.
      - layout: left
        title: Rindus
        link: https://www.rindus.de
        # link_text: boringcompany.com
        sub_title: Android Developer
        caption: November 2021 - Present
        quote: >
          Rindus, a Málaga, Spain-headquartered company helping companies to shape their development teams
        description: | # this will include new lines to allow paragraphs
            Providing service to Auxmoney partner as an Android Developer  
      - layout: left
        title: Ironhack
        link: https://www.ironhack.com/us
        # link_text: boringcompany.com
        sub_title: Kotlin/Java SME
        caption: May 2021 - April 2023
        quote: >
          Ironhack is a Global Tech School ranked top 2 worldwide, with multiple campuses worldwide
        description: | # this will include new lines to allow paragraphs
            While working at Ironhack as a contractor I was able to work on different educational projects as a Kotlin/Java Subject Matter Expert. I had to create Android/Kotlin educational content and teach about Java Spring Boot.
      - layout: left
        title: Freelance
        # link_text: boringcompany.com
        sub_title: Android Developer
        caption: May 2020 - April 2022
        description: | # this will include new lines to allow paragraphs
            During this period I worked as freelancer for several Android projects and contributed to open source projects as well.
      - layout: left
        title: Atos
        link: https://atos.net/en/
        # link_text: boringcompany.com
        sub_title: Knowledge Manager
        caption: April 2015 - May 2021
        quote: >
          Atos is a global leader in digital transformation
        description: | # this will include new lines to allow paragraphs
            I started as a L1 Helpdesk Agent. Then I moved to working as a technical writer/knowledge manager and also working on automation projects. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UNED
        caption: September 2021 - Present
        sub_title: Computer Science University Degree

      - layout: left
        title: KeepCoding
        caption: November 2020 - October 2021
        sub_title: XI Bootcamp FullStack Mobile

      - layout: left
        title: Centro Internacional Politécnico (CIP)
        caption: November 2016 - October 2019
        sub_title: Certificate of Higher Education in Multiplatform/Mobile Development

      - layout: left
        title: ULL / UNED
        caption: November 2011 - October 2016
        sub_title: Psychology University Degree

   #- title: When I'm Not Programming
    #layout: text
    #content: | # this will include new lines to allow paragraphs
    #  Alongside my interests software engineering some of my other interests and hobbies are:
    #  - Cooking

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
